/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DentistSignupRouteImport } from './routes/dentist-signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ProtectedDentistIndexRouteImport } from './routes/_protected/dentist/index'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistSignupRoute = DentistSignupRouteImport.update({
  id: '/dentist-signup',
  path: '/dentist-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const ProtectedDentistIndexRoute = ProtectedDentistIndexRouteImport.update({
  id: '/dentist/',
  path: '/dentist/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/auth': typeof AuthRoute
  '/dentist-signup': typeof DentistSignupRoute
  '/health': typeof HealthRoute
  '/dentist/': typeof ProtectedDentistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/auth': typeof AuthRoute
  '/dentist-signup': typeof DentistSignupRoute
  '/health': typeof HealthRoute
  '/dentist': typeof ProtectedDentistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dentist-signup': typeof DentistSignupRoute
  '/health': typeof HealthRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/_protected/dentist/': typeof ProtectedDentistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/dentist-signup' | '/health' | '/dentist/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dentist-signup' | '/health' | '/dentist'
  id:
    | '__root__'
    | '/(marketing)'
    | '/_protected'
    | '/auth'
    | '/dentist-signup'
    | '/health'
    | '/(marketing)/'
    | '/_protected/dentist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DentistSignupRoute: typeof DentistSignupRoute
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist-signup': {
      id: '/dentist-signup'
      path: '/dentist-signup'
      fullPath: '/dentist-signup'
      preLoaderRoute: typeof DentistSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/_protected/dentist/': {
      id: '/_protected/dentist/'
      path: '/dentist'
      fullPath: '/dentist/'
      preLoaderRoute: typeof ProtectedDentistIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedDentistIndexRoute: typeof ProtectedDentistIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDentistIndexRoute: ProtectedDentistIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DentistSignupRoute: DentistSignupRoute,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
