/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DentistRouteRouteImport } from './routes/dentist/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as DentistIndexRouteImport } from './routes/dentist/index'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as DentistServicesRouteImport } from './routes/dentist/services'
import { Route as DentistProfileRouteImport } from './routes/dentist/profile'
import { Route as DentistOnboardingRouteImport } from './routes/dentist/onboarding'
import { Route as DentistAppointmentsRouteImport } from './routes/dentist/appointments'
import { Route as marketingBookingsRouteImport } from './routes/(marketing)/bookings'
import { Route as marketingDentistsIdRouteImport } from './routes/(marketing)/dentists.$id'

const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistRouteRoute = DentistRouteRouteImport.update({
  id: '/dentist',
  path: '/dentist',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistIndexRoute = DentistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DentistRouteRoute,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const DentistServicesRoute = DentistServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DentistRouteRoute,
} as any)
const DentistProfileRoute = DentistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DentistRouteRoute,
} as any)
const DentistOnboardingRoute = DentistOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DentistRouteRoute,
} as any)
const DentistAppointmentsRoute = DentistAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DentistRouteRoute,
} as any)
const marketingBookingsRoute = marketingBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingDentistsIdRoute = marketingDentistsIdRouteImport.update({
  id: '/dentists/$id',
  path: '/dentists/$id',
  getParentRoute: () => marketingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dentist': typeof DentistRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/hello': typeof HelloRoute
  '/bookings': typeof marketingBookingsRoute
  '/dentist/appointments': typeof DentistAppointmentsRoute
  '/dentist/onboarding': typeof DentistOnboardingRoute
  '/dentist/profile': typeof DentistProfileRoute
  '/dentist/services': typeof DentistServicesRoute
  '/': typeof marketingIndexRoute
  '/dentist/': typeof DentistIndexRoute
  '/dentists/$id': typeof marketingDentistsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/hello': typeof HelloRoute
  '/bookings': typeof marketingBookingsRoute
  '/dentist/appointments': typeof DentistAppointmentsRoute
  '/dentist/onboarding': typeof DentistOnboardingRoute
  '/dentist/profile': typeof DentistProfileRoute
  '/dentist/services': typeof DentistServicesRoute
  '/': typeof marketingIndexRoute
  '/dentist': typeof DentistIndexRoute
  '/dentists/$id': typeof marketingDentistsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/dentist': typeof DentistRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/hello': typeof HelloRoute
  '/(marketing)/bookings': typeof marketingBookingsRoute
  '/dentist/appointments': typeof DentistAppointmentsRoute
  '/dentist/onboarding': typeof DentistOnboardingRoute
  '/dentist/profile': typeof DentistProfileRoute
  '/dentist/services': typeof DentistServicesRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/dentist/': typeof DentistIndexRoute
  '/(marketing)/dentists/$id': typeof marketingDentistsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dentist'
    | '/auth'
    | '/health'
    | '/hello'
    | '/bookings'
    | '/dentist/appointments'
    | '/dentist/onboarding'
    | '/dentist/profile'
    | '/dentist/services'
    | '/'
    | '/dentist/'
    | '/dentists/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/health'
    | '/hello'
    | '/bookings'
    | '/dentist/appointments'
    | '/dentist/onboarding'
    | '/dentist/profile'
    | '/dentist/services'
    | '/'
    | '/dentist'
    | '/dentists/$id'
  id:
    | '__root__'
    | '/(marketing)'
    | '/dentist'
    | '/auth'
    | '/health'
    | '/hello'
    | '/(marketing)/bookings'
    | '/dentist/appointments'
    | '/dentist/onboarding'
    | '/dentist/profile'
    | '/dentist/services'
    | '/(marketing)/'
    | '/dentist/'
    | '/(marketing)/dentists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  DentistRouteRoute: typeof DentistRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HealthRoute: typeof HealthRoute
  HelloRoute: typeof HelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist': {
      id: '/dentist'
      path: '/dentist'
      fullPath: '/dentist'
      preLoaderRoute: typeof DentistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist/': {
      id: '/dentist/'
      path: '/'
      fullPath: '/dentist/'
      preLoaderRoute: typeof DentistIndexRouteImport
      parentRoute: typeof DentistRouteRoute
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/dentist/services': {
      id: '/dentist/services'
      path: '/services'
      fullPath: '/dentist/services'
      preLoaderRoute: typeof DentistServicesRouteImport
      parentRoute: typeof DentistRouteRoute
    }
    '/dentist/profile': {
      id: '/dentist/profile'
      path: '/profile'
      fullPath: '/dentist/profile'
      preLoaderRoute: typeof DentistProfileRouteImport
      parentRoute: typeof DentistRouteRoute
    }
    '/dentist/onboarding': {
      id: '/dentist/onboarding'
      path: '/onboarding'
      fullPath: '/dentist/onboarding'
      preLoaderRoute: typeof DentistOnboardingRouteImport
      parentRoute: typeof DentistRouteRoute
    }
    '/dentist/appointments': {
      id: '/dentist/appointments'
      path: '/appointments'
      fullPath: '/dentist/appointments'
      preLoaderRoute: typeof DentistAppointmentsRouteImport
      parentRoute: typeof DentistRouteRoute
    }
    '/(marketing)/bookings': {
      id: '/(marketing)/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof marketingBookingsRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/dentists/$id': {
      id: '/(marketing)/dentists/$id'
      path: '/dentists/$id'
      fullPath: '/dentists/$id'
      preLoaderRoute: typeof marketingDentistsIdRouteImport
      parentRoute: typeof marketingRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingBookingsRoute: typeof marketingBookingsRoute
  marketingIndexRoute: typeof marketingIndexRoute
  marketingDentistsIdRoute: typeof marketingDentistsIdRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingBookingsRoute: marketingBookingsRoute,
  marketingIndexRoute: marketingIndexRoute,
  marketingDentistsIdRoute: marketingDentistsIdRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface DentistRouteRouteChildren {
  DentistAppointmentsRoute: typeof DentistAppointmentsRoute
  DentistOnboardingRoute: typeof DentistOnboardingRoute
  DentistProfileRoute: typeof DentistProfileRoute
  DentistServicesRoute: typeof DentistServicesRoute
  DentistIndexRoute: typeof DentistIndexRoute
}

const DentistRouteRouteChildren: DentistRouteRouteChildren = {
  DentistAppointmentsRoute: DentistAppointmentsRoute,
  DentistOnboardingRoute: DentistOnboardingRoute,
  DentistProfileRoute: DentistProfileRoute,
  DentistServicesRoute: DentistServicesRoute,
  DentistIndexRoute: DentistIndexRoute,
}

const DentistRouteRouteWithChildren = DentistRouteRoute._addFileChildren(
  DentistRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  DentistRouteRoute: DentistRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HealthRoute: HealthRoute,
  HelloRoute: HelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
